### ISSUE TITLE
这都是哪儿来的资料？

### ISSUE THREAD

**Issue by leo-liu** [qinglee/GEB#1]
我看图片什么的都很全而且质量很高，是 epub 电子书之类的东西？
就是编译费劲。

**Comment by qinglee** [comment]
来源在最后的制作信息那里有提到，就是[精益制作组的 epub](http://www.jebook.org/bbs/thread-717-1-1.html)。他们制作时很用心，对图片都进行了特殊处理。比如把图片的背景都调成了透明的，但也因此造成用 xelatex 编译后，adobe reader 在透明图片那一页的显示不正常：正文文字好像被加粗了一样。这是一个老问题了，如果在每一页使用下列 \special 语句

```
/Group << /S /Transparency /CS /DeviceRGB /I true>>
```

则每一页文字好像都被加粗过一样。我原来记的是这语句的作用是让被加粗页面的文字回归清晰，是我记错了么？

**Comment by nanmu42** [comment]
感谢前辈的贡献。:+1:

**Comment by xhmelon** [comment]
@qinglee 请问这些内容有版权问题么？

**Comment by leo-liu** [comment]
@tyfulcrum 还是在售的图书，当然有版权问题了。
和字幕组类似性质，将来好的去向就是收编。不过现在的书籍版权付费情况，电子书市场还是太难了。
